"""AI integration tests (ai.py).

No real API calls are made here: the unconfigured path is exercised for
real (returns None), and the success path is simulated with unittest.mock.
"""
import copy
import os
import sys
import unittest
from unittest import mock

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

import ai
import app as app_module
import data as data_module
from app import doctor_app, nurse_app, patient_app

BASELINE = copy.deepcopy(data_module.patients)

TEXT_FIELDS = ("patient_story", "ai_suggestion",
               "doctor_diagnosis", "nurse_instructions")


def claim(client, role):
    resp = client.get(f'/login?claim={role}')
    assert resp.status_code == 302
    return resp


class TestAIIntegration(unittest.TestCase):
    def setUp(self):
        for p, base in zip(data_module.patients, BASELINE):
            p.update({k: base[k] for k in TEXT_FIELDS})
            p['ai_source'] = ''
        app_module.reset_state()
        self.doctor_client = doctor_app.test_client()
        self.nurse_client = nurse_app.test_client()
        self.patient_client = patient_app.test_client()
        for c in (self.doctor_client, self.nurse_client, self.patient_client):
            c.testing = True

    def _patient(self, patient_id):
        return next(p for p in data_module.patients if p['id'] == patient_id)

    def test_redaction_strips_identifiers(self):
        text = "Mr Tan Ah Kow, NRIC S1234567A, call me at 9123 4567."
        out = ai.redact(text)
        self.assertNotIn("Tan Ah Kow", out)
        self.assertNotIn("S1234567A", out)
        self.assertNotIn("9123 4567", out)
        self.assertIn("[REDACTED-", out)

    def test_generate_suggestion_returns_none_without_api_key(self):
        with mock.patch.object(ai, "API_KEY", ""):
            self.assertIsNone(ai.generate_suggestion(self._patient(1)))

    def test_doctor_regenerates_suggestion_via_real_llm(self):
        """Simulated success: the LLM text replaces the static suggestion
        and the source label records the model."""
        with mock.patch("ai.generate_suggestion",
                        return_value="Consider urgent CT and BP monitoring."):
            with self.doctor_client as c:
                claim(c, 'doctor')
                resp = c.get('/ai_suggest/1')
                self.assertEqual(resp.status_code, 302)
                self.assertEqual(resp.headers.get('Location', ''), '/doctor')

        p = self._patient(1)
        self.assertEqual(p['ai_suggestion'], "Consider urgent CT and BP monitoring.")
        self.assertIn("generated by", p['ai_source'])
        self.assertIn("redacted", p['ai_source'])

    def test_fallback_when_llm_fails(self):
        """Simulated failure: the static suggestion survives and the page
        tells the doctor why."""
        with mock.patch("ai.generate_suggestion", side_effect=RuntimeError("boom")):
            with self.doctor_client as c:
                claim(c, 'doctor')
                resp = c.get('/ai_suggest/1')
                self.assertEqual(resp.status_code, 302)

        p = self._patient(1)
        self.assertEqual(p['ai_suggestion'], BASELINE[0]['ai_suggestion'])
        self.assertIn("fallback", p['ai_source'])

    def test_ai_route_only_exists_on_doctor_site(self):
        self.assertEqual(self.nurse_client.get('/ai_suggest/1').status_code, 404)
        self.assertEqual(self.patient_client.get('/ai_suggest/1').status_code, 404)

    def test_ai_route_requires_doctor_login(self):
        with self.doctor_client as c:
            resp = c.get('/ai_suggest/1')  # no session
            self.assertEqual(resp.status_code, 302)
            claim(c, 'doctor')
            resp = c.get('/ai_suggest/99')  # unknown patient
            self.assertEqual(resp.status_code, 302)
            self.assertEqual(resp.headers.get('Location', ''), '/doctor')


if __name__ == '__main__':
    unittest.main()
